package controller;

public enum Estate {
    NOT_SIGNED_UP,
    SIGNING_UP,
    MAIN_MENU,
    ADDING_NEW_TRANSACTION,
    ADMIN_PANEL,
    ADMIN_IS_ASKING_FOR_SOMEBODYS_TRANSACTIONS,
    ADMIN_IS_ADDING_NEW_TRANSACTION,
}
