package controller;

public enum MainMenuEstate {
    NOT_SIGNED_UP,
    SIGNING_UP,
    MAIN_MENU,
    ADDING_NEW_TRANSACTION,
    ASKING_FOR_TRANSACTION_INFO,
    ASKING_FOR_TRANSACTION_INFO_FOR_EDIT,
    ADMIN_PANEL,
    OPENING_USER_EDIT_TRANSACTION_PANEL,
    USER_EDIT_TRANSACTION_PANEL,
}
