package controller.adminpanel.adminEditTransactionPanel;

public enum AdminEditTransactionPanelEstate {
    ADMIN_EDIT_TRANSACTION_PANEL,
    ADMIN_SENDING_NEW_INVOICE_PHOTO,
    ADMIN_SENDING_NEW_AMOUNT,
    ADMIN_SENDING_NEW_DESCRIPTION,
    ADMIN_SENDING_NEW_FEE,
    ADMIN_SENDING_NEW_ADMIN_DESCRIPTION,
    ADMIN_SENDING_NEW_VERIFICATION_STATUS,
    ADMIN_SENDING_NEW_PAPER_INVOICE_STATUS,
}
