package controller.adminpanel.addtransactionpanel;

public enum AdminAddTransactionPanelEstate {
    ADMIN_ADD_TRANSACTION_PANEL,
    ADMIN_IS_ADDING_NEW_INCOME_TRANSACTION,
    ADMIN_IS_ADDING_NEW_GIVE_TO_USERS_TRANSACTION_SENDING_INFO,
    ADMIN_IS_ADDING_NEW_GIVE_TO_USERS_TRANSACTION_SENDING_USER_ID,
    ADMIN_IS_ADDING_NEW_EXPENDITURE_TRANSACTION_SENDING_INFO,
    ADMIN_IS_ADDING_NEW_EXPENDITURE_TRANSACTION_SENDING_USER_ID,
}
