package controller.adminpanel;

public enum AdminPanelEstate {
    ADMIN_PANEL,
    ADMIN_IS_ASKING_FOR_SOMEBODYS_TRANSACTIONS,
    ADMIN_IS_ADDING_NEW_TRANSACTION,
    ADMIN_IS_ADDING_NEW_TRANSACTION_SENDING_USER_ID,
    LISTS_PANEL,
    ADMIN_EDIT_TRANSACTION_PANEL,
    ASKING_FOR_TRANSACTION_INFO,
    ASKING_FOR_TRANSACTION_INFO_FOR_EDIT,
}
