package controller.adminpanel;

public enum AdminPanelEstate {
    ADMIN_PANEL,
    LISTS_PANEL,
    ADMIN_EDIT_TRANSACTION_PANEL,
    ASKING_FOR_TRANSACTION_INFO,
    ASKING_FOR_TRANSACTION_INFO_FOR_EDIT,
    ADD_DELETE_ADMINS_PANEL,
    ADMIN_ADD_TRANSACTION_PANEL,
    ADMIN_IS_ADDING_NEW_USER_SENDING_NAME,
    ADMIN_IS_ADDING_NEW_USER_FORWARDING_MESSAGE,
}
