package controller.useredituserinfopanel;

public enum UserEditUserInfoPanelEstate {
    USER_EDIT_USER_INFO_PANEL,
    USER_IS_SENDING_NEW_NAME,
    USER_IS_SENDING_NEW_EMAIL,
    USER_IS_SENDING_NEW_PHONE_NUMBER,
    USER_IS_SENDING_NEW_CARD_NUMBER,
    USER_IS_SENDING_NEW_ACCOUNT_NUMBER,
    USER_IS_SENDING_NEW_SHABA_NUMBER
}
